# This is a basic workflow to help you get started with Actions

name: Publish master to NPM

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request close events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTOMATION_TOKEN }}
